export enum Sets {
    "Basic",
    "Classic",
    "Credits",
    "Naxxramas",
    "Debug",
    "Goblins vs Gnomes",
    "Missions",
    "Promotion",
    "Reward",
    "System",
    "Blackrock Mountain",
    "Hero Skins",
    "Tavern Brawl",
    "The Grand Tournament",
}